### ISSUE TITLE
Conditionally render attributes DSL

### ISSUE THREAD

**Issue by uxxman** [codenoble/cache-crispies#31]
First of all great work. Great performance gains with clear and concise DSL. 👍 

Currently the function for conditionally rendering attributes can easily get out of hand if you have a few checks. They don't quite feel right inside a proc. example

```ruby
show_if -> (model, options) { model.published? && options[:current_user].admin? && options[:current_user].active? && options[:current_user].id == model.user_id } do
  serialize :published_at
end
```

Can we have something like rails callback filters, the above example would become

```ruby
show if: :include_published_at? do
  serialize :published_at
end

def include_published_at?
  model.published? &&
  options[:current_user].admin?  &&
  options[:current_user].active? &&
  options[:current_user].id == model.user_id
end
```

**Comment by adamcrown** [comment]
Thanks for the PR. It's merged so I'm closing this.
